spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/criptopulse
    username: root
    password: rootpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

app:
  default-user-id: 11111111-1111-1111-1111-111111111111